version: '3.8'
services:
  api:
    build: ./backend
    container_name: mern_back_c
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/backend # relative path
      - /backend/node_modules # crear volumen de la carpeta node_modules
  web:
    build: ./frontend
    container_name: mern_front_c
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
  